### PR TITLE
get transactions as pandas dataframe

### PR DESCRIPTION
**Pull request by adamgreenhall**

### CODE REVIEW

**Comment by mrooney** [comment]
Awesome, thanks! Is this something that might make sense from the command line as well? Perhaps either dumping the CSV to stdout, or serializing to JSON? If so it would be awesome to add that to the main() method with the other command-line options and update the README.

**Comment by mrooney** [comment]
Let me know your thoughts @adamgreenhall , I'd love to get this merged as it has been requested before :)

**Comment by adamgreenhall** [comment]
@mrooney - can do. will work on that this morning.

**Comment by adamgreenhall** [comment]
@mrooney - think this is ready now. review?

**Comment by mrooney** [comment]
Great thanks, I'll get this merged @adamgreenhall :) Does the setup.py entry_points mean we don't need the bin/mintapi anymore? I wasn't familiar with this feature but it looks neat.

**Comment by adamgreenhall** [comment]
yup - with the entry_points added, after you install, you can call mintapi directly from the bash shell.

**Comment by mrooney** [comment]
Perfect, thanks, I removed the bin/ directory which we don't need now. There were two small bugs I fixed that you may want to review at https://github.com/mrooney/mintapi/commit/432fc2ed0b83ed62c3a7873e9b8ed7eac584afa8. Particularly, if no filename was specified with transactions, it crashed because the second wasn't an elif and it tried to call endswith() on None. And second, if you didn't specify a csv or json extension, it silently did nothing. Do these make sense? Thanks again for your awesome contribution!

**Comment by mrooney** [comment]
And, this is merged and released as 1.6 :D

**Comment by adamgreenhall** [comment]
looks good - thanks!

**Pull request closed without merging**
