### PR TITLE
Suppress pandas future warning

### PR DESCRIPTION
**Pull request by dzg**

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks! Can you show what the normal warning is and explain why it makes sense to ignore it?

**Comment by dzg** [comment]
> Thanks! Can you show what the normal warning is and explain why it makes sense to ignore it?

When I run my data grabber from shell, I get:
`/usr/local/lib/python3.7/site-packages/mintapi/api.py:694: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead`

I'm using it as part of bitbar, so it returns an error.

**Comment by mrooney** [comment]
Is it not possible to just update the code to import numpy directly instead of hiding a valid warning? Just curious. Thanks for your efforts!

**Comment by dzg** [comment]
> Is it not possible to just update the code to import numpy directly instead of hiding a valid warning? Just curious. Thanks for your efforts!

In my tests, `import numpy` did not help with the error message.

**Comment by nelsonauner** [comment]
I am also pro updating code instead of hiding a valid warning. I've updated the code in https://github.com/mrooney/mintapi/pull/211

**Comment by mrooney** [comment]
Thanks, will close in favor of #211, thanks for bringing this to my attention though, greatly appreciated :)

**Pull request closed without merging**
