### PR TITLE
Fixing get_transactions() call using old session syntax

### PR DESCRIPTION
**Pull request by zabracks**
The get_transactions() call was using the self.session.get(...) syntax, but this doesn't work now that the class inherits from requests.Session.

Fixed and tested locally, but didn't write tests, only because test coverage is fairly low on this project anyway.

### CODE REVIEW

**Comment by mrooney** [comment]
Great catch, thank you! I'm not sure I follow all the changes, any particular reason why https://github.com/mrooney/mintapi/commit/4faeb7dc1e6f1d2d1a8d69cef0c5134051b3cef8 wouldn't be all that is necessary? It seems to work on my end, apologies if I'm totally misunderstanding what you are trying to accomplish :)

**Comment by ianlevesque** [comment]
For what it's worth it was broken for me too without this change.

**Comment by ianlevesque** [comment]
The single linked commit I mean.

**Comment by mrooney** [comment]
Great, should be fixed and released as 1.8! If there are other cool features your pull request address @zabracks , please do open a pull request explaining them and I'll happily review them!

**Comment by zabracks** [comment]
Sorry, made the pull request, then kept on developing without thinking! 

I found a different method to get transactions from a JSON blob rather than the csv. The majority of the other commits deal with that.



Drew Worthey

**Pull request closed without merging**
