### PR TITLE
add history to get_budget

### PR DESCRIPTION
**Pull request by robwil**
I took #94  and merged latest master so that it can be finally merged. Only merge conflicts were:
* keeping get_categories at top since it's used in both the new history if branch and the original code (now in else branch)
* reformatting the cmdline parsing option to fit the new style of that code section

### CODE REVIEW

**Comment by robwil** [comment]
@mrooney can you take a look when you get a chance? Thanks

**Comment by mrooney** [comment]
Thanks, looks nice! Do you mind just adding a line to the README to document usage?

**Comment by robwil** [comment]
@mrooney added the option to the README

**Comment by mrooney** [comment]
Thanks for your contribution, looks great!

**Pull request merged**
