### PR TITLE
Add ability to get messages about accounts that need attention

### PR DESCRIPTION
**Pull request by jorythompson**
Added ability to get attention message from Mint.  
Changed test script to be able to add parameters from the command line.
updated options to chrome_options
added conversion of credit score from string to int

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks, I'll peek at this shortly and see if I can figure out the CI error.

**Comment by jorythompson** [comment]
> Thanks, I'll peek at this shortly and see if I can figure out the CI error.

any luck with the Travis error?

**Comment by mrooney** [comment]
> > Thanks, I'll peek at this shortly and see if I can figure out the CI error.
> 
> any luck with the Travis error?

Hey Jory, I am able to reproduce this locally just running `nosetests` in this branch but not in master, so it isn't anything specific to Travis or master. So this appears to be some kind of return value or method signature changed and this is a real error in the PR.

**Comment by jorythompson** [comment]
I give up.  
I've put the main function back the way it was and my branch runs fine from the command line (I was not able to get nose working on my macbook).

**Comment by tsdg112** [comment]
Please don't delete lines 61 and 62 in README.md.

**Pull request closed without merging**
