### PR TITLE
Fix for Sign In Method With Two Workflows

### LINKED ISSUE #232: ElementNotInteractableException during MFA
Hello,

Love this repo. I created my own app for scraping the Mint web page and have been using it for a year or so on my Windows machine. Then I ran into this problem while trying to get it working on a raspberry pi 4. And now I am seeing it on both my windows and RPi machines. I've not touched the code on the Windows machine so I'm wondering if something changed at Mint.com.

I am using SMS to authenticate. In the code below, by this point, it has logged in with my credentials and Mint.com has texted me the MFA code. 

Inside api.py: get_web_driver: 

            else:
                driver.find_element_by_id('ius-mfa-options-form')
                driver.implicitly_wait(10)  # seconds [Note: I added this with no effect ]
                try:
                    mfa_method_option = driver.find_element_by_id('ius-mfa-option-{}'.format(mfa_method))
                    driver.implicitly_wait(10)  # seconds [Note: I added this with no effect ]
                    mfa_method_option.click()
 
I have verified that mfa_method == sms so it is trying to find the ius-mfa-option-sms element, and seems to have found it successfully. But when the click is applied on the last line above, it takes an ElementNotInteractableException. I looked this exception up and saw suggestions about putting in some delay to allow the page to load, so I added a driver.implicitly_wait(10) but no help. 

Here is the version information for the Pi OS, chrome driver, chrome browser, and mintapi. 

pi@raspberrypi:~ $ cat /usr/lib/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"

pi@raspberrypi:~ $ apt list chromium-driver
Listing... Done
chromium-driver/stable 83.0.4103.116-1~deb10u2 armhf

pi@raspberrypi:~ $ apt list chromium-browser
Listing... Done
chromium-browser/testing,now 84.0.4147.105-rpt2 armhf [installed,automatic]

pi@raspberrypi:~ $ pip show mintapi
Name: mintapi
Version: 1.44

Thanks for any help! Regards,

### PR DESCRIPTION
**Pull request by jaron-l**
This merge request uses the code in merge request #233 

This issue aims to fix #232 and in addition allowing mintapi to sign in if username and password are on two separate pages or not (both can happen at time of writing).

Summary:
1. Broke the sign in process and getting a web driver at mint.com from get_web_driver into _sign_in and _create_web_driver_at_mint_com for ease of testing
2. Made a try/except loop to detect if username and password are on the same page or not
3. Allowed the sms button to not necessarily be clicked if it is not required (I didn't remove the old method because I wasn't sure if sometimes mint.com would supply that workflow. I never saw it but it still could happen.)
4. Added test_args.json to .gitignore and made tests.py try to read that for test arguments. I would love feedback on doing this. I did this as an attempt to allow developers to pass in their credentials to the tests to make the tests automatable. I initially tried using command line arguments, but that method breaks vscodes test specifier (and I imagine other IDEs too).
5. Also added .vscode and chromedriver to .gitignore for ease for developers.

### CODE REVIEW

**Review by mrooney — CHANGES_REQUESTED** [review]
Thanks, really great PR! Would you mind resubmitting without the various whitespace changes? Unless they are failing flake8 or similar tests, I would really prefer to not add spaces and line breaks in various places unrelated to the PR, especially as they are style choices I don't use elsewhere. Thanks again and looking forward to merging!

**Comment by jaron-l** [comment]
Sure thing. They got added in because I broke the flake8 pipeline job and because I was lazy, I just ran autopep8 on it. I'll remove the unnecessary changes.

**Review by mrooney — APPROVED** [review]
Looks great, thanks for your time and effort!

**Comment by revelario** [comment]
Great job, everybody. I re-installed with pip (to 1.50) and was able to get `headless=False` working with a manual click on SMS in the browser popup. However, I was not able to get `headless=True` working like it used to before the Mint login change. Automated login seems to hang/spin, and I'm wondering if mintapi is not detecting the MFA prompt. Anybody experiencing the same issue? Chrome 93.0.4577.82.

**Comment by jaron-l** [comment]
@revelario you should probably ask this on the discord or in a separate issue so more people can see it. Feel free to post in one of those two and I'd be happy to respond.

**Pull request merged**
