### PR TITLE
Handle MFA

### PR DESCRIPTION
**Pull request by eschizoid**
* Download Chrome driver and allow headless drivers.
* Handle MFA, and wait for sync after login.
* Default `--mfa-method=sms` in case the user does not specify it

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks! Does this supersede https://github.com/mrooney/mintapi/pull/135?

**Comment by eschizoid** [comment]
@mrooney yes, is a combination of both efforts.

**Comment by eschizoid** [comment]
Hey @mrooney, any idea when this will be merged down?

**Comment by mrooney** [comment]
Okay I gave it a code and functional review, overall pretty awesome! Thanks again for the hard work.

- [ ] Can we either make SMS be the default behavior, or require --mfa-method when using --headless? I don't like the idea of having default behavior that is "unlikely to work."

That is, let's either fail fast at the argument parsing phase or give them a useful behavior and print a debug message that we are using sms because they didn't explicitly specify an --mfa-method. Whichever you feel is best :) Then I will give it a merge and release!

**Comment by eschizoid** [comment]
@mrooney Sounds good, will take care of that anytime soon.

**Comment by eschizoid** [comment]
@mrooney PR comments addressed, let me know what you think

**Comment by mrooney** [comment]
Thanks! README just needs a change to reflect that sms is default, but I'll merge this for now to get it in and try to do that myself later. Great work :) I will bump the version and release as well.

**Comment by mrooney** [comment]
Thanks again, this is fantastic, merged and released to pypi as 1.30!

**Pull request merged**
